### ISSUE TITLE
添加自定义声音 不起到作用

### ISSUE THREAD

**Issue by DNetORM** [JiangJuHong/FlutterXiaoMiPushPlugin#3]
在res/raw目录下添加了一个自定义MP3格式的声音
 .extra(Constants.EXTRA_PARAM_SOUND_URI, "android.resource://test.xiao_mi_push_plugin_example/raw/slow_spring_board")
但是这个自定义声音不起到作用，依然还是采用的默认声音。

**Comment by JiangJuHong** [comment]
你好，本插件基于原生SDK提供Flutter接口，目前仅支持如下接口
![image](https://user-images.githubusercontent.com/17740963/93306203-23267e80-f832-11ea-9799-520466f30d93.png)

**Comment by JiangJuHong** [comment]
如果没有其它疑问，我将关闭此 Issues，在需要时可以重新打开
