### ISSUE TITLE
Meet exception when call Method 'getMeid' in android.telephony.TelephonyManager@b941ad0

### ISSUE THREAD

**Issue by jk-zhang** [JiangJuHong/FlutterXiaoMiPushPlugin#5]
遇到了一个提示
小米推送后台也没有看到新增用户

V/xiaomi  (29699): [Thread:6630] get region from system, region = CN
W/JavaCalls(29699): Meet exception when call Method 'getMeid' in android.telephony.TelephonyManager@b941ad0
W/JavaCalls(29699): java.lang.reflect.InvocationTargetException
W/JavaCalls(29699): 	at java.lang.reflect.Method.invoke(Native Method)
W/JavaCalls(29699): 	at com.xiaomi.push.bd.b(Unknown Source:16)
W/JavaCalls(29699): 	at com.xiaomi.push.bd.a(Unknown Source:0)
W/JavaCalls(29699): 	at com.xiaomi.push.i.g(Unknown Source:117)
W/JavaCalls(29699): 	at com.xiaomi.mipush.sdk.MiPushClient.initialize(Unknown Source:682)
W/JavaCalls(29699): 	at com.xiaomi.mipush.sdk.MiPushClient.access$100(Unknown Source:0)
W/JavaCalls(29699): 	at com.xiaomi.mipush.sdk.MiPushClient$1.run(Unknown Source:13)
W/JavaCalls(29699): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:462)
W/JavaCalls(29699): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
W/JavaCalls(29699): 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
W/JavaCalls(29699): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
W/JavaCalls(29699): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)

**Comment by jk-zhang** [comment]
getRegId() 得到的结果为 NULL

**Comment by JiangJuHong** [comment]
抱歉，通过以上日志无法对错误进行定位。
您可以提供：
    1. 复现步骤
    2. 完整的错误日志
来帮助错误定位。

**Comment by jk-zhang** [comment]
解决啦，是因为包名没对上导致的
我通过Demo发现 XiaoMiPushPlugin.addListener事件监听
然后找到了问题的原因~

Demo 真是个好东西 (来自菜鸟的心声)

**Comment by clstech** [comment]
包名没对上， 可以贴一下嘛，我包名都对，可是还是和你情况一样，但是重启几次又可以用
