### ISSUE TITLE
Adding a translation

### ISSUE THREAD

**Issue by guyluz11** [JiangJuHong/FlutterXiaoMiPushPlugin#9]
I'm sure a lot of flutter programs would love to use this package to push notifications to Xiaomi devices.
Xiaomi have its own implementation of notifications which is different from Android, so an English version of the readme would be very appreciated.

As written here 
https://pub.dev/packages/flutter_local_notifications
![Screenshot_20230317_115906_Firefox](https://user-images.githubusercontent.com/9304740/225873521-6d4087a5-94b2-40e0-8274-f0c50bdfc9ec.jpg)

**Comment by JiangJuHong** [comment]
Yes, I will choose your suggestion. If I have time, I will internationalize the file.

**Comment by JiangJuHong** [comment]
It has been revised and it is now available in both Chinese and English formats
